# Generated by Django 6.0.2 on 2026-02-11 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prog_code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cutoff_2018', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cutoff_2019', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cutoff_2020', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cutoff_2021', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cutoff_2022', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cutoff_2023', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cutoff_2024', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cutoff_2025', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['institution__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CareerPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('required_skills', models.TextField()),
                ('average_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_courses', models.ManyToManyField(blank=True, related_name='career_paths', to='careers.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='careers.institution'),
        ),
    ]
