# Generated by Django 6.0.2 on 2026-02-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='career_field',
            field=models.CharField(blank=True, default='', help_text='e.g., Engineering, Medicine, Computer Science, Business', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='min_grade',
            field=models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D+', 'D+'), ('D', 'D'), ('D-', 'D-'), ('E', 'E')], default='C', help_text='Minimum mean grade required for admission', max_length=2),
        ),
        migrations.AddField(
            model_name='course',
            name='required_subjects',
            field=models.JSONField(blank=True, default=list, help_text="e.g., ['MATHEMATICS', 'PHYSICS', 'CHEMISTRY']"),
        ),
    ]
