# Generated by Django 6.0.1 on 2026-02-07 09:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_profile_email_remove_profile_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_subjects', models.JSONField(blank=True, default=list)),
                ('preferred_career_fields', models.JSONField(blank=True, default=list)),
                ('preferred_institutions', models.JSONField(blank=True, default=list)),
                ('location_preference', models.CharField(blank=True, max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='students.profile')),
            ],
            options={
                'verbose_name_plural': 'Student Preferences',
            },
        ),
        migrations.CreateModel(
            name='StudentGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('ENGLISH', 'English'), ('KISWAHILI', 'Kiswahili'), ('MATHEMATICS', 'Mathematics'), ('BIOLOGY', 'Biology'), ('CHEMISTRY', 'Chemistry'), ('PHYSICS', 'Physics'), ('HISTORY', 'History'), ('GEOGRAPHY', 'Geography'), ('CRE', 'Christian Religious Education'), ('IRE', 'Islamic Religious Education'), ('HRE', 'Hindu Religious Education'), ('FRENCH', 'French'), ('GERMAN', 'German'), ('ARABIC', 'Arabic'), ('HOME_SCIENCE', 'Home Science'), ('AGRICULTURE', 'Agriculture'), ('WOODWORK', 'Woodwork'), ('METALWORK', 'Metalwork'), ('BUILDING_CONSTRUCTION', 'Building Construction'), ('POWER_MECHANICS', 'Power Mechanics'), ('ELECTRICITY', 'Electricity'), ('DRAWING_DESIGN', 'Drawing and Design'), ('AVIATION', 'Aviation Technology'), ('COMPUTER', 'Computer Studies'), ('BUSINESS', 'Business Studies'), ('MUSIC', 'Music'), ('ART_DESIGN', 'Art and Design')], max_length=100)),
                ('grade', models.CharField(choices=[('A', 'A - 12 points'), ('A-', 'A- - 11 points'), ('B+', 'B+ - 10 points'), ('B', 'B - 9 points'), ('B-', 'B- - 8 points'), ('C+', 'C+ - 7 points'), ('C', 'C - 6 points'), ('C-', 'C- - 5 points'), ('D+', 'D+ - 4 points'), ('D', 'D - 3 points'), ('D-', 'D- - 2 points'), ('E', 'E - 1 point')], max_length=10)),
                ('points', models.IntegerField(editable=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.profile')),
            ],
            options={
                'ordering': ['-points'],
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
