# Generated by Django 6.0.2 on 2026-02-24 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riasec_categories', models.JSONField(default=list, help_text='Top RIASEC categories at time of recommendation')),
                ('avg_grade', models.FloatField(default=0.0, help_text="Student's average grade at time of recommendation")),
                ('strong_subjects', models.JSONField(default=list, help_text='Subjects with B+ or above at time of recommendation')),
                ('matched_career_fields', models.JSONField(default=list, help_text='Career fields matched from RIASEC + grades + preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveIntegerField(help_text='ID of the recommended course or institution')),
                ('item_type', models.CharField(choices=[('course', 'Course'), ('institution', 'Institution')], help_text='Whether this is a course or institution recommendation', max_length=20)),
                ('item_name', models.CharField(help_text='Name of the recommended course or institution', max_length=255)),
                ('score', models.FloatField(default=0.0, help_text='Relevance score from ML engine (0.0 to 1.0)')),
                ('recommendation_type', models.CharField(choices=[('content_based', 'Content Based'), ('collaborative', 'Collaborative Filtering'), ('hybrid', 'Hybrid')], default='hybrid', max_length=20)),
                ('match_reasons', models.JSONField(blank=True, default=list, help_text='List of reasons why this was recommended')),
                ('is_seen', models.BooleanField(default=False)),
                ('is_saved', models.BooleanField(default=False, help_text='Student bookmarked this recommendation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['user', 'item_type'], name='recommendat_user_id_b5be89_idx'), models.Index(fields=['user', 'is_seen'], name='recommendat_user_id_71e42d_idx'), models.Index(fields=['user', 'is_saved'], name='recommendat_user_id_e4785b_idx')],
                'unique_together': {('user', 'item_id', 'item_type')},
            },
        ),
    ]
