# Generated by Django 6.0.1 on 2026-02-09 07:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_studentpreferences_studentgrades'),
    ]

    operations = [
        migrations.CreateModel(
            name='PsychometricQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('category', models.CharField(choices=[('REALISTIC', 'Realistic'), ('INVESTIGATIVE', 'Investigative'), ('ARTISTIC', 'Artistic'), ('SOCIAL', 'Social'), ('ENTERPRISING', 'Enterprising'), ('CONVENTIONAL', 'Conventional'), ('OPENNESS', 'Openness'), ('CONSCIENTIOUSNESS', 'Conscientiousness'), ('EXTRAVERSION', 'Extraversion'), ('AGREEABLENESS', 'Agreeableness'), ('NEUROTICISM', 'Neuroticism')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PsychometricResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_value', models.IntegerField(help_text='1=Strongly Disagree, 5=Strongly Agree', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.psychometricquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychometric_responses', to='students.profile')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('student', 'question')},
            },
        ),
    ]
